version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: